### ISSUE TITLE
Error 404 Fetching JSON data from Movie API

### ISSUE THREAD

**Issue by thefiend** [jgaa/restc-cpp#51] opened 2018-03-11 07:45 UTC
Hi, I am trying to fetch movie information from a Movie API. However, I get 

> libc++abi.dylib: terminating with uncaught exception of type restc_cpp::HttpNotFoundException: Request failed with HTTP error: 404 Not Found

trying to do so and wish to know how do I change the struct to fit the API.

E.g.
<img width="1381" alt="screen shot 2018-03-11 at 3 42 57 pm" src="https://user-images.githubusercontent.com/3714496/37250970-f2b6b680-2542-11e8-928b-a748700ec4a6.png">

```
#include <iostream>

#include <boost/lexical_cast.hpp>
#include <boost/fusion/adapted.hpp>

#include "restc-cpp/restc-cpp.h"
#include "restc-cpp/RequestBuilder.h"

using namespace std;
using namespace restc_cpp;

struct Movie {
    int page = 0;
    int total_results = 0;
    int total_pages = 0;
};

BOOST_FUSION_ADAPT_STRUCT(
        Movie,
        (int, page)
        (int, total_results)
        (int, total_pages)
)

int main() {
    auto rest_client = RestClient::Create();
    Movie found_movies = rest_client->ProcessWithPromiseT<Movie>([&](Context& ctx) {
                
                Movie movie;

                SerializeFromJson(movie,
                                  RequestBuilder(ctx)
                                          .Get("https://api.themoviedb.org/3/search/movie?api_key=30ac911b5a4841e65d905a53b31396ae&query=Jack+Reacher")
                                          .Header("X-Client", "RESTC_CPP")
                                          .Header("X-Client-Purpose", "Testing")
                                          .Execute());

                return movie;
            }).get();

    cout << "Number of Results " << found_movies.total_results << ", Page: " << found_movies.page << endl;
}
```

**Comment by jgaa** [comment] 2018-03-11 10:41
I'll have a look at it

**Comment by jgaa** [comment] 2018-03-11 12:00
The url you provide will be encoded, and that will prevent the server to decode the authentication token.

Try 
```C++
                            SerializeFromJson(movie,
                                  RequestBuilder(ctx)
                                          .Get("http://api.themoviedb.org/3/search/movie")
                                          .Argument("api_key", "30ac911b5a4841e65d905a53b31396ae")
                                          .Argument("query", "Jack+Reacher")
                                          .Header("X-Client", "RESTC_CPP")
                                          .Header("X-Client-Purpose", "Testing")
                                          .Execute());
```
The Argument() functions will make sure that the arguments are sent correctly.

You should 'git pull' restc-cpp, as I found and fixed a bug wen I checked tis.

**Comment by thefiend** [comment] 2018-03-11 12:52
I have pulled and installed the restc-cpp library and used the code above. However, I am getting an error from SerializeJson.

`Assertion failed: (false), function DoRecurseToMember, file /usr/local/include/restc-cpp/SerializeJson.h, line 704.`

**Comment by jgaa** [comment] 2018-03-11 13:17
I would put the results in a structure and then and then add it as:
```C++
struct Movie {
    int page = 0;
    int total_results = 0;
    int total_pages = 0;
    std::vector<Results> results;
}

BOOST_FUSION_ADAPT_STRUCT(
        Movie,
        (int, page)
                (int, total_results)
                (int, total_pages)
        (std::vector<Results>, results)
)
```

Make sure that Movie has the same member, as you map directly from C++ data-type and name. 

You can have a look at [this header](https://github.com/Syniverse/Messaging-C-Plus-Plus/blob/master/include/scgapi/Contact.h) to see some more complex mappings.

**Comment by thefiend** [comment] 2018-03-11 13:58
I am getting Exit code 11 from this
```
struct Results {
    int vote_count= 0;
    int id= 0;
    bool video;
    double vote_average;
    string title;
    double popularity;
    string poster_path;
    string original_language;
    string original_title;
    bool adult;
    string overview;
    string release_date;
};

struct Movie {
    int page = 0;
    int total_results = 0;
    int total_pages = 0;
    std::vector<Results> results;
};

BOOST_FUSION_ADAPT_STRUCT(
        Movie,
        (int, page)
                (int, total_results)
                (int, total_pages)
                (std::vector<Results>, results)
)
```

**Comment by jgaa** [comment] 2018-03-11 13:59
I'll take a look

**Comment by jgaa** [comment] 2018-03-11 15:49
Since you are serializing Results, you need to declare that as well :)

```C++
BOOST_FUSION_ADAPT_STRUCT(
    Results,
    (int, vote_count)
    (int, id)
    (bool, video)
    (double, vote_average)
    (string, title)
    (double, popularity)
    (string, poster_path)
    (string, original_language)
    (string, original_title)
    (bool, adult)
    (string, overview)
    (string, release_date)
)
```

I have committed an assert for that case, and a fix where restc-cpp needs to ignore an array (genre_ids). So you should 'git poll' before testing again.

**Comment by thefiend** [comment] 2018-03-11 16:07
Awesome! Got it to work. Thank you very much. Really appreciate it. :D

**Comment by thefiend** [comment] 2018-03-11 16:13
I tried querying other movies such as Titanic and Black Panther and got this exception.
`Assertion failed: (current_name_.empty()), function DoKey, file /usr/local/include/restc-cpp/SerializeJson.h, line 1024.`

**Comment by jgaa** [comment] 2018-03-11 17:07
That's interesting.
Can you share with me the request URL's or the json payloads from this requests? (curl can give you the payload from the command-line).

**Comment by thefiend** [comment] 2018-03-11 18:00
It is the same as above just that I changed .Argument("query", "Jack+Reacher") to .Argument("query", "titanic")

**Comment by jgaa** [comment] 2018-03-11 20:19
I'll take a look at it tomorrow. It might be a bug.

**Comment by thefiend** [comment] 2018-03-12 11:44
Did I declare the array genre_id wrongly?

**Comment by jgaa** [comment] 2018-03-12 16:58
I can reproduce it. Trying to figure out what's triggering the error.

**Comment by jgaa** [comment] 2018-03-12 17:58
You found another bug! I have committed a fix.

This list could actually be implemented as an iterator, where you loop over the content. That would allow huge result-sets. I have implemented that for one project, and been thinking about doing it in a more general fashion. If I get time in the near future, I'll see if I can use this movie API as one of the examples for such a general feature. 

Thank you for digging out these bugs btw. If this was a commercial project there would have been a QA person spending considerable time figuring out how to crash the library - but with free, open source, I have to relay on my own imagination and real life cases reported by users.

**Comment by thefiend** [comment] 2018-03-12 18:25
Great! Really thankful that you made it work.  I will be trying to get it to work with Twitter API next, to pull tweets from Twitter. Any idea how to authorize request on twitter API with this library?

**Comment by jgaa** [comment] 2018-03-13 04:50
I don't really understand why these services keeps using OAuth. It's been broken (insecure) for a long time. 

Anyway, using it requires cryptographic signing of headers and content in a very specific way. I think it should be done by restc-cpp as the process is complex and will take time to comprehend an implement. It's documented here: https://developer.twitter.com/en/docs/basics/authentication/guides/authorizing-a-request

The general OAuth 1.0 protocol is documented here: https://oauth.net/core/1.0/#anchor9

I don't have time to implement this right away, but I'll put it on my list.

**Closed** 2018-03-13 16:09 UTC
